GET http://localhost:5000/users
Authorization: Beareer

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "Pajrin",
  "password": "test1234"
}

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Fajrin Alifian",
    "password": "pajrin4321",
    "confPassword": "pajrin4321"
}

###
DELETE http://localhost:5000/logout/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyLCJ1c2VybmFtZSI6IlBhanJpbiIsImlhdCI6MTcyMDYyMTU2OSwiZXhwIjoxNzIwNjI4NzY5fQ.rJT8fGr2El0hZXKumkLiIeRNvhYNIg6_UWD--AVlx0I

###
POST http://localhost:5000/karyawan/add
Content-Type: application/json

{
    "nik": "324234242342",
    "nidn": "121334141",
    "id_ktp": "31700030234",
    "nama": "Pajrinz",
    "gelar_dp": "Dr.",
    "gelar_bl": ".skom",
    "agama": "ISLAM",
    "tgl_lahir": "01-03-2002",
    "tmp_lahir": "Jakarta",
    "gol_darah": "O",
    "st_karyawan": "tetap",
    "st_nikah": "belum menikah",
    "alamat": "Avenue 21th road, NYC",
    "telp": "082210380323",
    "npwp": "213132103912312323",
    "tgl_masuk": "02-04-2024"
}

###
GET http://localhost:5000/karyawan/get

###
GET http://localhost:5000/karyawan/count

###
PUT http://localhost:5000/karyawan/update
Content-Type: application/json

{
    "searchBy": "nama",
    "searchValue": "pajrin",
    "updateField": "nik",
    "newValue": "211211313139"
}

###
GET http://localhost:5000/karyawan/search?searchBy=nama&searchTerm=kiki
Content-Type: application/json

###
GET http://localhost:5000/karyawan/getmonthly

###
DELETE http://localhost:5000/karyawan/delete?nik=20201210
Content-Type: application/json